### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by massicottec** [massicottec/poke-feels-movie-edition#1]
#Home Page

##User Story
AS AN user with a movie watching dilemma
I WANT to generate six suggested movie titles to watch based on my team of six pokemon team choice
SO THAT I can clear my movie dilemma

##Acceptance Criteria
GIVEN I need movie suggestions
WHEN I access the homepage
THEN I am greeted with a clear run down of the purpose of the website.

**Comment by RdySetShine** [comment]
added css properties for the homepage to adjust symmetry throughout website
