### ISSUE TITLE
Readme generation

### ISSUE THREAD

**Issue by massicottec** [massicottec/poke-feels-movie-edition#17]
# Readme Generation

##User Story
AS AN user with a movie watching dilemma
I WANT to generate six suggested movie titles to watch based on my team of six pokemon team choice
SO THAT I can clear my movie dilemma

##Acceptance Criteria
GIVEN I need movie suggestions
WHEN I check the readme file
THEN I am given a brief idea of what the webpage does

**Comment by Keegan-Omel** [comment]
I created a ReadMe.md

**Comment by Keegan-Omel** [comment]
just have to add screen shots of finished site.
