### ISSUE TITLE
Pokemon user input boxes

### ISSUE THREAD

**Issue by massicottec** [massicottec/poke-feels-movie-edition#5]
# Pokemon Input Boxes

##User Story
AS a user who wants to enter a team of six pokemon
I WANT to generate six text input boxes 
SO THAT I can enter my six pokemon of choice

##Acceptance Criteria
GIVEN I am linked to and presented with six text input boxes on the submission-page
WHEN I click on a text input box 
THEN I can enter a name of a pokemon as one of my choices

**Comment by Keegan-Omel** [comment]
I added six user input boxes
